name: Workflow CI - Process Worker

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
env:
  GO_VERSION: '1.23.0'

jobs:
  test-and-quality:
    name: Test and Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Run tests with coverage
      run: |
        go test -coverprofile=coverage.out -covermode=atomic ./...
        go tool cover -func=coverage.out

    - name: Check coverage threshold
      run: |
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "Coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE <= 80" | bc -l) )); then
          echo "❌ Coverage is below 80% (current: $COVERAGE%)"
          exit 1
        else
          echo "✅ Coverage is above or equal to 80% (current: $COVERAGE%)"
        fi

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=fiap-challenger-soat
          -Dsonar.projectKey=fiap-challenger-soat_hackthon-soat-process-worker
          -Dsonar.go.coverage.reportPaths=coverage.out
          -Dsonar.coverage.exclusions=**/*_test.go,**/mocks/**,**/cmd/**,**/vendor/**
          -Dsonar.test.inclusions=**/*_test.go
          -Dsonar.coverage.minimum=80
          -Dsonar.qualitygate.wait=true

    - name: Quality Gate Check
      run: |
        echo "✅ CI/CD Pipeline completed successfully"
        echo "📊 Coverage threshold of 80% has been enforced"
        echo "🔍 SonarQube analysis passed" 